pipeline:
  build:
    image: ruby
    commands:
      - bundle install
      - RAILS_ENV=test bundle exec rake db:migrate
      - RAILS_ENV=test bundle exec rake
  docker:
    image: plugins/docker
    repo: registry.quan.io/dan/breath
    registry: registry.quan.io
    secrets: [ docker_username, docker_password ]
    branches: [ master ]
    tags:
      - latest
      - "${DRONE_COMMIT_SHA:0:8}"
