kind: pipeline
name: default

steps:
# - name: test
#   image: ruby
#   environment:
#     RAILS_ENV: test
#   commands:
#     - bundle install
#     - bundle exec rake db:migrate
#     - bundle exec rake
# - name: docker
#   when:
#     branch:
#     - master
#   image: plugins/docker
#   settings:
#     repo: reg.quan.io/dan/breath
#     tags:
#       - latest
#       - ${DRONE_COMMIT_SHA}
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#     registry: reg.quan.io
- name: deploy - migrate db
  image: reg.quan.io/dan/drone-kubectl:latest
  when:
  branch:
  - master
  settings:
    kubernetes_server:
      from_secret: kubernetes_host
    kubernetes_cert:
      from_secret: kubernetes_crt
    kubernetes_token:
      from_secret: kubernetes_token
  commands:
    - kubectl apply -f kubernetes/migrate_job.yaml
    - sleep 50
    - kubectl wait --for=condition=complete -f kubernetes/migrate_job.yaml
    - kubectl delete -f kubernetes/migrate_job.yaml
- name: deploy - app
  image: reg.quan.io/dan/drone-kubectl:latest
  when:
  branch:
  - master
  settings:
    kubernetes_server:
      from_secret: kubernetes_host
    kubernetes_cert:
      from_secret: kubernetes_crt
    kubernetes_token:
      from_secret: kubernetes_token
  commands:
    - kubectl apply -f kubernetes/application.yaml

image_pull_secrets:
- dockerconfigjson
