kind: pipeline
name: default

steps:
- name: test
  image: ruby
  environment:
    RAILS_ENV: test
  when:
    branch:
    - master
  commands:
    - bundle install
    - bundle exec rake db:migrate
    - bundle exec rake
- name: docker
  when:
    branch:
    - master
    event:
    - push
  image: plugins/docker
  settings:
    repo: reg.quan.io/dan/breath
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: reg.quan.io
- name: deploy - migrate db
  image: reg.quan.io/dan/drone-kubectl:latest
  when:
    branch:
    - master
    event:
    - push
  settings:
    kubernetes_server:
      from_secret: kubernetes_host
    kubernetes_cert:
      from_secret: kubernetes_crt
    kubernetes_token:
      from_secret: kubernetes_token
  commands:
    - sed -ie "s/latest/$DRONE_COMMIT_SHA/" kubernetes/migrate_job.yaml
    - kubectl apply -f kubernetes/migrate_job.yaml
    - sleep 50
    - kubectl wait --for=condition=complete -f kubernetes/migrate_job.yaml
    - kubectl delete -f kubernetes/migrate_job.yaml
- name: deploy - app
  image: reg.quan.io/dan/drone-kubectl:latest
  when:
    branch:
    - master
    event:
    - push
  settings:
    kubernetes_server:
      from_secret: kubernetes_host
    kubernetes_cert:
      from_secret: kubernetes_crt
    kubernetes_token:
      from_secret: kubernetes_token
  commands:
    - sed -ie "s/latest/$DRONE_COMMIT_SHA/" kubernetes/application.yaml
    - sed -ie "s/DEPLOY_TIME/$(date)/" kubernetes/application.yaml
    - cat kubernetes/application.yaml
    - kubectl apply -f kubernetes/application.yaml

image_pull_secrets:
- dockerconfigjson
