image: ruby

stages:
  - test
  - artifact

rake:
  stage: test
  script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake

push_to_dockerhub:
  stage: artifact
  tags:
  - host
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.quan.io
  - docker build -t registry.quan.io/dan/breath:$CI_COMMIT_SHA .
  - docker push registry.quan.io/dan/breath:$CI_COMMIT_SHA

