image: ruby

before_script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:migrate

rake:
  script: 
  - RAILS_ENV=test bundle exec rake

docker_build:
  script:
  - docker build -t registry.quan.io/dan/breath
  - docker push registry.quan.io/dan/breath
