image: ruby

stages:
  - build
  - test

docker_build:
  stage: build
  tags:
  - host
  script: 
  - docker build -t registry.quan.io/dan/breath:$CI_COMMIT_SHA .
  - docker push registry.quan.io/dan/breath:$CI_COMMIT_SHA

rake:
  stage: test
  image: registry.quan.io/dan/breath:$CI_COMMIT_SHA
  script: 
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake
