image: ruby

stages:
  - test
  - push

docker_build:
  stage: test
  tags:
  - host
  script: 
  - docker build -t registry.quan.io/dan/breath:$CI_COMMIT_SHA .

rake:
  stage: test
  script: 
  - bundle install
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake

docker_push:
  stage: push
  tags:
  - host
  script:
    - docker push registry.quan.io/dan/breath:$CI_COMMIT_SHA
