image: ruby

rake:
  script: 
  - bundle install
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake

docker_build:
  tags:
  - host
  script:
  - docker build -t registry.quan.io/dan/breath
  - docker push registry.quan.io/dan/breath
