---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: breath
  namespace: default
spec:
  selector:
    matchLabels:
      app: breath
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: breath
        k8s-app: breath
    spec:
      containers:
      - name: breath
        image: registry.quan.io/dan/breath:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 3
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: breath-service
  namespace: default
spec:
  selector:
    k8s-app: breath
  ports:
    - protocol: TCP
      port: 3000
      name: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: breath
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: breath.quan.io
    http:
      paths:
      - backend:
          serviceName: breath-service
          servicePort: 3000
