version: "3"
services:
  breath:
    image: registry.quan.io/dan/breath:latest
    restart: always
    ports:
      - "3000:3000"
    command: ["bundle", "exec", "puma", "-p3000", "-eproduction"]
    network_mode: "host"
    environment:
      - RAILS_ENV=production
    env_file:
      - /secrets/breath/secrets.env
