version: "2.1"

services:
  breath:
    image: registry.quan.io/dan/breath:latest
    restart: always
    ports:
      - "3000:3000"
    command: ["bundle", "exec", "puma", "-p3000", "-eproduction"]
    environment:
      - POSTGRES_HOST=postgres
    env_file:
      - /secrets/breath/secrets.env
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    restart: always
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data"
