development:
  adapter: postgresql
  database: breath_development
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: breath_production
  encoding: unicode
  pool: 5
  timeout: 5000
  username: breath
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5433") %>
