apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: breath
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: drone-deploy
  namespace: breath
rules:
  - apiGroups: ["extensions", "batch"]
    resources: ["deployments", "jobs"]
    verbs: ["get","list","patch","update", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: drone-deploy
  namespace: breath
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: breath
roleRef:
  kind: Role
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io
